controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '|en|fr'
    defaults:
        _locale: '%locale%'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
