#index:
#    path: /
#    controller: App\Controller\DefaultController::index

build:
  path: /
  controller : App\Controller\BuildController::index

create:
  path: /create
  controller : App\Controller\CreateBuildController::index

setlocale:
  path: /setlocale/{locale}
  controller : App\Controller\SetLocalController::index