on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Composer Install Dependencies
      uses: php-actions/composer@v5
      with:
        version: 2
        php_version: 7.3
        dev: no

    - name: Composer Swtch Production
      uses: php-actions/composer@v5
      with:
        version: 2
        php_version: 7.3
        dev: no
        command: dump-env
        args: prod

    - name: Rsync Upload
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_SSH_KEY}}
      with:
        flags: '-av --delete '
        options: '--exclude-from=exclude'
        src: './'
        dest: 'nwbuser@51.195.45.151:~/nwb/'