on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rsync Upload
      uses: Pendect/action-rsyncer@v1.1.0
      env:
        DEPLOY_KEY: ${{secrets.DEPLOY_SSH_KEY}}
      with:
        flags: '-av --delete'
        options: '--exclude-from=exclude'
        src: './'
        dest: 'nwbuser@51.195.45.151:~/nwb/'
    - name: Composer
      uses: appleboy/ssh-action@master
      with:
        host: '51.195.45.151'
        username: 'nwbuser'
        key: ${{secrets.DEPLOY_SSH_KEY}}
        script: |
          cd ~/nwb/
          composer dump-env prod
          composer update
          php bin/console cache:clear

