on:
  release:
    types: [published]
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - uses: MilesChou/composer-action@master
          with:
            args: update --no-dev --no-cache -oa
        - uses: MilesChou/composer-action@master
          with:
            args: dump-env prod --no-cache
            
        - uses: actions/setup-node@v1
          with:
            node-version: 10
        - run: npm install
        - run: npm run build
            
        - uses: sand4rt/ftp-deployer@v1.3
          with:
            host: ${{ secrets.FTP_SERVER }} # e.g. ftp.host.com or sftp.host.com (without ftp:// or ftps://)
            username: ${{ secrets.FTP_USERNAME }} # FTP username
            password: ${{ secrets.FTP_PASSWORD }} # FTP password
            remote_folder: www/
            local_folder: ./
            cleanup: false # optional, remove existing files inside FTP remote folder
            exclude: "['.git/**', '.github/**', 'node_modules/**', 'assets/**', 'var/**', 'migrations/', 'public/bundles/apiplatform/**', '.env', '.gitignore', '.prettierignore', '.prettierrc', 'composer.json', 'composer.lock', 'exclude', 'package', 'postcss.config.js', 'README.md', 'start.bat', 'start.sh', 'symfony.lock', 'webpack.config.js', 'yarn.lock']"
            pasive: true # optional
