on:
  release:
    types: [published]
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: baschny/php-composer-action@v1
          with:
            command: update --no-dev --no-cache
        - uses: baschny/php-composer-action@v1
          with:
            command: dump-env prod
        - uses: actions/setup-node@v1
          with:
            node-version: 10
        - run: npm install
        - run: npm run build
        - uses: sebastianpopp/ftp-action@releases/v2
          with:
            host: ${{ secrets.FTP_SERVER }}
            user: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            localDir: "./"
            remoteDir: "www"
            options: "--delete --asci"
