on:
  release:
    types: [published]
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - uses: MilesChou/composer-action@master
          with:
            args: update --no-dev --no-cache -oa
        - uses: MilesChou/composer-action@master
          with:
            args: dump-env prod --no-cache
            
        - uses: actions/setup-node@v1
          with:
            node-version: 10
        - run: npm install
        - run: npm run build
        
        - uses: sebastianpopp/ftp-action@releases/v2
          with:
            host: ${{ secrets.FTP_SERVER }}
            user: ${{ secrets.FTP_USERNAME }}
            password: ${{ secrets.FTP_PASSWORD }}
            localDir: "./"
            remoteDir: "www"
            options: "--delete --asci"
