on:
  release:
    types: [published]
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - uses: MilesChou/composer-action@master
          with:
            args: update --no-dev --no-cache -oa
        - uses: MilesChou/composer-action@master
          with:
            args: dump-env prod --no-cache
            
        - uses: actions/setup-node@v1
          with:
            node-version: 10
        - run: npm install
        - run: npm run build
            
        - uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
          with:
            ftp_host: ${{ secrets.FTP_SERVER }}
            ftp_username: ${{ secrets.FTP_USERNAME }}
            ftp_password: ${{ secrets.FTP_PASSWORD }}
            local_source_dir: "./"
            dist_target_dir: "www/"
            exclude: "'^.git/' '^.github/' '^node_modules/' '^assets/' '^var/' '^migrations/' '^public/bundles/apiplatform/' '^.env' '^.gitignore' '^.prettierignore' '^.prettierrc' '^composer.lock' '^exclude' '^package-lock.json' '^package.json' '^postcss.config.js' '^README.md' '^start.bat' '^start.sh' '^symfony.lock' '^webpack.config.js' '^yarn.lock'"
